# Generated by Django 4.2.1 on 2024-10-18 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ordercust_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 2, 7, 58, 171021)),
        ),
        migrations.AddField(
            model_name='ordercust',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 2, 7, 58, 169027)),
        ),
        migrations.AddField(
            model_name='ordersup',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 2, 7, 58, 171021)),
        ),
    ]
