# Generated by Django 4.2.1 on 2024-10-23 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_invoice_date_ordercust_date_ordersup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 9, 28, 55, 43338)),
        ),
        migrations.AlterField(
            model_name='ordercust',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 9, 28, 55, 41344)),
        ),
        migrations.AlterField(
            model_name='ordersup',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 9, 28, 55, 42341)),
        ),
        migrations.AlterField(
            model_name='ordersupitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
